#!/usr/bin/env python3

import argparse
import booklet_splitter


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='For a given pdf, builds booklets to be printed, '
                                                 'folded and eventualy assembled as a book')
    parser.add_argument('input_pdf', type=str, nargs=1, help='PDF file to be sliced as booklets')
    parser.add_argument('--max_size', type=int, default=32)
    parser.add_argument('--min_size', type=int, default=16)
    parser.add_argument('--cover', dest='cover', action='store_true',
                        help='Adds a page at the very beginning and at the very end, to paste a cover')
    args = parser.parse_args()

    input_pdf = booklet_splitter.PdfHandler(args.input_pdf[0])
    print(input_pdf)
    myPages = booklet_splitter.compute_effective_pages(input_pdf.numPages, args.cover)
    print(myPages)
    booklets = booklet_splitter.compute_booklets(myPages, args.min_size, args.max_size)
    print(booklets)
    constituted_booklets = input_pdf.fill_booklets('booklet{0:02d}.pdf', booklets, args.cover)
    #print(constituted_booklets)
    booklet_splitter.booklet_ordering(constituted_booklets)
    input_pdf.merge(constituted_booklets)
    input_pdf.write_booklets(constituted_booklets)
