#!/usr/bin/env python

import click
import booklet_splitter
import logging


@click.command(
    help="For a given pdf, builds booklets to be printed, "
    "folded and eventualy assembled as a book"
)
@click.option(
    "--max_size",
    type=int,
    default=32,
    show_default=True,
    help="Max size for a booklet, must be multiple of 4",
)
@click.option("--log", default="INFO", show_default=True, help="Log level at execution")
@click.option(
    "--targetdir",
    default=".",
    show_default=True,
    help="Directory where the booklets PDF are written",
)
@click.option(
    "--layout",
    type=bool,
    default=True,
    show_default=True,
    help="Only splits your document in booklets",
)
@click.option(
    "--cover",
    type=bool,
    default=True,
    show_default=True,
    help="Adds a page at the very beginning and at the very end, to paste a cover",
)
@click.argument("input_pdf")
def cmd(
    max_size: int, input_pdf: str, log: str, targetdir: str, layout: bool, cover: bool
):
    logging.basicConfig(level=logging.getLevelName(log))
    booklet_splitter.generate_booklets(input_pdf, cover, layout, max_size, targetdir)


cmd()
